# golangci-lint configuration for notebook
# See https://golangci-lint.run/usage/configuration/ for all options
version: "2"

run:
  timeout: 5m
  # Note: For CI, use 'golangci-lint run --tests=false' to skip test files
  # Test files are excluded from funlen/gocognit via exclusions below
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  sort-order:
    - file
  show-stats: true

linters:
  exclusions:
    rules:
      # Exclude linters in test files
      - path: '(.+)_test\.go'
        linters:
          - errcheck
          - gosec
          - gocritic
          - gocyclo
          - funlen
          - gocognit
          - govet
          - goconst
          - nilnil     # Mock implementations often return nil, nil
          - tparallel  # Not all test structures benefit from t.Parallel

      # Exclude deprecation warnings in tests
      - path: '(.+)_test\.go'
        text: "SA1019:"

      # Exclude long lines with go:generate
      - linters:
          - lll
        source: "^//go:generate "

    # Warn if exclusion rule is never used
    warn-unused: true

  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - govet         # Standard Go vet checks
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Find unused code

    # Additional recommended linters
    - misspell      # Find commonly misspelled words
    - revive        # Fast, configurable, extensible linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - gosec         # Security-focused linter
    - gocritic      # Opinionated linter with many checks
    - bodyclose     # Check HTTP response body is closed
    - noctx         # Find http requests without context
    - errname       # Check error naming conventions
    - errorlint     # Find code that will cause problems with Go 1.13+ error wrapping
    - copyloopvar   # Check for pointers to loop variables (replaces exportloopref for Go 1.22+)
    - gochecknoinits # Check for init functions
    - goconst       # Find repeated strings that could be constants
    - gocyclo       # Check cyclomatic complexity
    - goprintffuncname # Check printf-like function names
    - nakedret      # Check for naked returns in long functions
    - nilerr        # Find code returning nil even when error is not nil
    - nilnil        # Check for returning nil values with nil errors
    - predeclared   # Find code shadowing predeclared identifiers
    - thelper       # Detect test helpers without t.Helper()
    - tparallel     # Check for t.Parallel() usage
    - whitespace    # Check for unnecessary whitespace
    - gocognit      # Check cognitive complexity
    - funlen        # Check function length

  disable:
    - godox         # Don't fail on TODO/FIXME comments
    - lll           # Line length is subjective and formatting handles it

  settings:
    errcheck:
      # Check for ignored errors from specific functions
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close

    govet:
      enable:
        - shadow      # Report shadowed variables
      disable:
        - fieldalignment  # Can be overly strict

    gocyclo:
      min-complexity: 15

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - commentFormatting
        - unnamedResult
        - hugeParam        # Interface signatures often require value types
        - rangeValCopy     # Minor performance impact, cleaner code

    revive:
      rules:
        - name: var-naming
          disabled: false
        - name: exported
          disabled: false
        - name: indent-error-flow
          disabled: false
        - name: blank-imports
          disabled: false
        - name: context-as-argument
          disabled: false
        - name: dot-imports
          disabled: false
        - name: error-return
          disabled: false
        - name: error-strings
          disabled: false
        - name: error-naming
          disabled: false
        - name: if-return
          disabled: false
        - name: increment-decrement
          disabled: false
        - name: var-declaration
          disabled: false
        - name: package-comments
          disabled: true  # Can be too strict for internal packages
        - name: range
          disabled: false
        - name: receiver-naming
          disabled: false
        - name: time-naming
          disabled: false
        - name: unexported-return
          disabled: false
        - name: errorf
          disabled: false
        - name: empty-block
          disabled: false
        - name: superfluous-else
          disabled: false
        - name: unused-parameter
          disabled: false
        - name: unreachable-code
          disabled: false
        - name: redefines-builtin-id
          disabled: false

    gosec:
      excludes:
        - G307  # Can be too strict about defer Close()

    gocognit:
      min-complexity: 23

    funlen:
      lines: 60
      statements: 40

    nakedret:
      max-func-lines: 30

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0
